### ISSUE TITLE
Verify all agents for all sims working

### ISSUE THREAD

**Issue by ShvetankPrakash** [srivatsankrishnan/oss-arch-gym#26]
It appears many agents are not working out of the box. We should verify all of them and add the necessary documentation,

**Comment by ShvetankPrakash** [comment]
For example:
```
$ python train_randomwalker_DRAMSys.py 
Traceback (most recent call last):
  File "/home/oss-arch-gym/sims/DRAM/train_randomwalker_DRAMSys.py", line 11, in <module>
    from arch_gym.envs import dramsys_wrapper
  File "/home/oss-arch-gym/arch_gym/envs/dramsys_wrapper.py", line 19, in <module>
    from acme import specs
ImportError: cannot import name 'specs' from 'acme' (unknown location)
```
We need to add something like `os.sys.path.insert(0, os.path.abspath('../../acme'))` like in `train_ppo.py` under `sims/DRAM`

**Comment by ShvetankPrakash** [comment]
Noting here that @manan-garg1504 is working with @aadyapipersenia04 to add acme to install script for this issue

**Comment by manan-garg1504** [comment]
@AditiR-42 I was trying to run astra-sim after a clean install, but now the submodule cloning fails:
```
$ git submodule update --init --recursive  sims/AstraSim/astrasim-archgym
fatal: remote error: upload-pack: not our ref 53574d2f1d20e26d5143eb0ff0c98b6af338da61
fatal: Fetched in submodule path 'sims/AstraSim/astrasim-archgym', but it did not contain 53574d2f1d20e26d5143eb0ff0c98b6af338da61. Direct fetching of that commit failed.
```
Does the documentation need to be updated?
